apiVersion: skaffold/v2beta11
kind: Config
build:
requires:
- path: ./setup
- path: ./accounts-db
- path: ./contacts
- path: ./frontend
- path: ./ledger-db
- path: ./ledgerwriter
- path: ./userservice
- path: ./transactionhistory
- path: ./balancereader
- path: ./loadgenerator
