apiVersion: skaffold/v2beta11
kind: Config
build:
requires:
- path: ./setup
- path: ./accounts-db
  activeProfiles:                                     
  - name: cloudbuild
    activatedBy: ["cloudbuild"]
- path: ./contacts
  activeProfiles:                                     
  - name: cloudbuild
    activatedBy: ["cloudbuild"]
- path: ./frontend
  activeProfiles:                                     
  - name: cloudbuild
    activatedBy: ["cloudbuild"]
- path: ./ledger-db
  activeProfiles:                                     
  - name: cloudbuild
    activatedBy: ["cloudbuild"]
- path: ./ledgerwriter
  activeProfiles:                                     
  - name: cloudbuild
    activatedBy: ["cloudbuild"]
- path: ./userservice
  activeProfiles:                                     
  - name: cloudbuild
    activatedBy: ["cloudbuild"]
- path: ./transactionhistory
  activeProfiles:                                     
  - name: cloudbuild
    activatedBy: ["cloudbuild"]
- path: ./balancereader
  activeProfiles:                                     
  - name: cloudbuild
    activatedBy: ["cloudbuild"]
- path: ./loadgenerator

profiles:
- name: cloudbuild
